spring:
  application:
    name: collector
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: false
        serviceId: config-server
      fail-fast: false
      enabled: false
  kafka:
    bootstrap-servers: ${spring.kafka.bootstrap-servers:localhost:9092}

server:
  port: ${server.port:8080}

collector:
  kafka:
    topics:
      sensors: ${collector.kafka.topics.sensors:telemetry.sensors.v1}
      hubs: ${collector.kafka.topics.hubs:telemetry.hubs.v1}

grpc:
  server:
    port: ${grpc.server.port:59091}

eureka:
  client:
    enabled: ${eureka.client.enabled:false}
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/

logging:
  level:
    ru.yandex.practicum.kafka.telemetry: ${logging.level.ru.yandex.practicum.kafka.telemetry:INFO}