spring:
  application:
    name: aggregator
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/

aggregator:
  kafka:
    topics:
      sensors: telemetry.sensors.v1
      snapshots: telemetry.snapshots.v1
    consumer:
      group-id: aggregator-group

logging:
  level:
    ru.yandex.practicum.kafka.telemetry: INFO

