spring:
  application:
    name: analyzer
  datasource:
    url: ${ANALYZER_DB_URL:jdbc:postgresql://localhost:5432/analyzer}
    username: ${ANALYZER_DB_USERNAME:analyzer}
    password: ${ANALYZER_DB_PASSWORD:analyzer}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

kafka:
  topics:
    snapshots: ${KAFKA_SNAPSHOTS_TOPIC:telemetry.snapshots.v1}
    hubs: ${KAFKA_HUBS_TOPIC:telemetry.hubs.v1}
  consumer:
    snapshots-group-id: ${KAFKA_SNAPSHOTS_GROUP_ID:analyzer-snapshots}
    hubs-group-id: ${KAFKA_HUBS_GROUP_ID:analyzer-hubs}
    poll-timeout-ms: ${KAFKA_POLL_TIMEOUT_MS:500}

grpc:
  client:
    hub-router:
      address: ${HUB_ROUTER_GRPC_ADDRESS:static://localhost:59090}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  level:
    ru.yandex.practicum.kafka.telemetry: INFO

