spring:
  application:
    name: analyzer
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:8080/mydatabase
    username: postgres
    password: 123qweasd
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

kafka:
  topics:
    hubs: telemetry.hubs.v1
    snapshots: telemetry.snapshots.v1
  consumer:
    hub-events:
      group-id: analyzer-hub-events-group
    snapshots:
      group-id: analyzer-snapshots-group

logging:
  level:
    ru.yandex.practicum.kafka.telemetry: INFO

