server:
  port: 8080

spring:
  application:
    name: collector
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/

collector:
  kafka:
    topics:
      sensors: telemetry.sensors.v1
      hubs: telemetry.hubs.v1

grpc:
  server:
    port: 59091

logging:
  level:
    ru.yandex.practicum.kafka.telemetry: DEBUG

